apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mop-backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    github.com/project-slug: gudo11y/mop-backstage
    'backstage.io/kubernetes-id': mop-backstage
spec:
  type: service
  owner: beengud
  lifecycle: production
